from airflow import DAG
from airflow.providers.google.cloud.operators.bigquery import BigQueryExecuteQueryOperator
from airflow.operators.empty import EmptyOperator 
from datetime import datetime
from airflow.utils.dates import days_ago
from airflow.operators.trigger_dagrun import TriggerDagRunOperator

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 3,
}

with DAG(
        dag_id='transform_load_db_emr_to_bq',
        default_args=default_args,
        description="Darwin Box EMR Data transform Table Load",
        schedule_interval=None,  
        start_date=days_ago(1),
        catchup=False,
    tags=['ather-pops', 'dev', 'db-staging-emr-load','1'],
    ) as dag:

        start_task = EmptyOperator(
            task_id='start_task'
        )

        backup_tr_db_emr = BigQueryExecuteQueryOperator(
            task_id='backup_tr_db_emr',
            sql="""             
        CREATE
        OR REPLACE TABLE `tt-sandbox-002.transform.tr_db_emr_temp` AS
        SELECT * FROM `tt-sandbox-002.transform.tr_db_emr`;
        """ ,
            use_legacy_sql=False
        )

        db_emr_transform_load = BigQueryExecuteQueryOperator(
            task_id='db_emr_transform_load',
            sql=""" 
            
        truncate table `tt-sandbox-002.transform.tr_db_emr`;

        CREATE TEMP TABLE db_temp_timestamp AS
        SELECT
            CURRENT_TIMESTAMP() AS ts;

        INSERT INTO
            `tt-sandbox-002.transform.tr_db_emr` (
                employee_id,
                employee_status,
                employee_type,
                full_name,
                company_email_id,
                first_name,
                middle_name,
                last_name,
                activated_by,
                activated_by_name,
                activated_by_id,
                activation_timestamp,
                admin_deactivate_reason,
                admin_deactivation_type,
                attendance_policy,
                attendance_shift,
                attendance_shift_shift_block_effective_date,
                attendance_weeklyoff,
                band,
                confirmation_status,
                confirmation_status_without_hold_days,
                continuous_service_date,
                created_by,
                created_by_name,
                created_by_id,
                current_attendance_shift,
                date_of_confirmation,
                date_of_confirmation_without_hold_days,
                date_of_exit,
                date_of_reactivation,
                date_of_activation,
                date_of_joining,
                deactivation_timestamp,
                departments_hierarchy_with_codes,
                department_name,
                department_code,
                function_name,
                function_code,
                tp_lead_email_id,
                ta_lead_email_id,
                rnd_tag,
                factory_tag,
                direct_manager_effective_from,
                direct_manager_email_id,
                direct_manager_employee_id,
                direct_manager_name,
                do_not_hire_comment,
                employee_added_date,
                employee_separation_comments,
                employee_separation_reason,
                employee_type_effective_from,
                hod_name,
                hod_email_id,
                hod_employee_id,
                hrbp_email_id,
                hrbp_employee_id,
                hrbp_name,
                job_family,
                job_sub_family,
                job_level,
                job_level_code,
                l2_manager_name,
                l2_manager_email_id,
                l2_manager_employee_id,
                latest_manager_effective_from,
                latest_modified,
                latest_modified_timestamp,
                latest_modified_any_attribute,
                latest_office_effective_from,
                level,
                notice_period_assigned,
                notice_period_start_date,
                old_employee_id_rehired,
                past_work_experience,
                pay_scale,
                pay_scale_group,
                performance_manager,
                performance_manager_name,
                performance_manager_id,
                permission_role,
                probation_period,
                retirement_date,
                retirement_date_manual,
                role,
                role_code,
                role_effective_from,
                role_name,
                salary_structure,
                separation_agreed_last_date,
                separation_final_recovery_days,
                separation_reject_reason,
                separation_requested_last_date,
                separation_revoke_date,
                separation_revoke_reason,
                separation_status,
                separation_transaction_date,
                termination_comment,
                vertical,
                vertical_code,
                base_office_location,
                blood_group,
                candidate_id,
                city_type,
                date_of_birth,
                date_of_birth_access,
                date_of_resignation_recorded,
                date_of_resignation,
                emergency_contact_number,
                emergency_contact_person,
                emergency_contact_relation,
                location_type,
                marital_status,
                marriage_anniversary_access,
                office_area,
                office_city,
                office_country,
                office_location,
                office_pincode,
                office_state,
                office_city_code,
                office_country_code,
                office_state_code,
                phone_country_code,
                primary_mobile_number,
                primary_mobile_country_code,
                user_unique_id,
                work_area_code,
                citizenship,
                experience_prior_to_ather_round_off,
                fathers_name,
                food_allowance,
                job_title,
                personal_email_id,
                physical_work_location,
                r_d_project_1,
                r_d_project_1_contribution,
                r_d_project_2,
                r_d_project_2_contribution,
                r_d_project_3,
                r_d_project_3_contribution,
                r_d_project_4,
                r_d_project_4_contributions,
                r_d_project_5,
                r_d_project_5_contribution,
                special_leave_2022,
                swimlane_1,
                swimlane_1_contribution,
                swimlane_2,
                swimlane_2_contribution,
                swimlane_3,
                swimlane_3_contribution,
                swimlane_4,
                swimlane_4_contribution,
                swimlane_5,
                swimlane_5_contribution,
                current_address,
                current_address_line_1,
                current_pin_code,
                current_city,
                current_city_code,
                current_country,
                current_country_code,
                current_landmark,
                current_state,
                current_state_code,
                current_street,
                office_mobile_access,
                permanent_address,
                permanent_address_line_1,
                permanent_pin_code,
                permanent_city,
                permanent_city_code,
                permanent_country,
                permanent_country_code,
                permanent_district_code,
                permanent_landmark,
                permanent_region_code,
                permanent_state,
                permanent_state_code,
                permanent_street,
                personal_email_id_access,
                personal_mobile_access,
                personal_mobile_no,
                home,
                office,
                personal,
                office_mobile_no,
                gender,
                start_date,
                end_date,
                load_timestamp
            )
        SELECT
            st.employee_id,
            st.employee_status,
            st.employee_type,
            st.full_name,
            st.company_email_id,
            st.first_name,
            st.middle_name,
            st.last_name,
            st.activated_by,
            REGEXP_EXTRACT (st.activated_by, r'^(.*) \(') AS activated_by_name,
            REGEXP_EXTRACT (st.activated_by, r'\((.*?)\)') AS activated_by_id,
            DATETIME(TIMESTAMP(PARSE_TIMESTAMP('%d-%b-%Y %H:%M:%S', st.activation_timestamp)), 'Asia/Kolkata') AS activation_timestamp,

            st.admin_deactivate_reason,
            st.admin_deactivation_type,
            st.attendance_policy,
            st.attendance_shift,
            st.attendance_shift_shift_block_effective_date,
            st.attendance_weeklyoff,
            st.band,
            st.confirmation_status,
            st.confirmation_status_without_hold_days,
            st.continuous_service_date,
            st.created_by,
            REGEXP_EXTRACT (st.created_by, r'^(.*) \(') AS created_by_name,
            REGEXP_EXTRACT (st.created_by, r'\((.*?)\)') AS created_by_id,
            st.current_attendance_shift,
            st.date_of_confirmation,
            st.date_of_confirmation_without_hold_days,
            st.date_of_exit,
            st.date_of_reactivation,
            st.date_of_activation,
            st.date_of_joining,
            DATETIME(TIMESTAMP(PARSE_TIMESTAMP('%d-%b-%Y %H:%M:%S', st.deactivation_timestamp)), 'Asia/Kolkata') AS deactivation_timestamp,

            st.departments_hierarchy_with_codes,
            COALESCE(
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'\|\s*([^\(]+)'
                )),
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'^(.*?)\s*\('
                )),
                st.departments_hierarchy_with_codes
            ) AS department,
            COALESCE(
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'.*\(([^)]+)\)$'
                )),
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'\((\w+)\)'
                ))
            ) AS department_code,
            COALESCE(
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'^(.*?)\s*\('
                )),
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'\|\s*([^\(]+)'
                ))
            ) AS FUNCTION,
            COALESCE(
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'\((\w+)\)'
                )),
                TRIM(REGEXP_EXTRACT (
                    st.departments_hierarchy_with_codes,
                    r'.*\(([^)]+)\)$'
                ))
            ) AS function_code,
            vdf.tp_lead_email_id,
            vdf.ta_lead_email_id,
            vdf.rnd_tag,
            vdf.factory_tag,
            st.direct_manager_effective_from,
            st.direct_manager_email,
            st.direct_manager_employee_id,
            REGEXP_EXTRACT (st.direct_manager, r'^(.*) \(') AS direct_manager_name,
            st.do_not_hire_comment,
            st.employee_added_date,
            st.employee_separation_comments,
            st.employee_separation_reason,
            st.employee_type_effective_from,
            REGEXP_REPLACE (st.hod, r'\s*\(.*?\)', '') AS hod,
            st.hod_email_id,
            st.hod_employee_id,
            st.hrbp_email_id,
            st.hrbp_employee_id,
            hrbp.full_name,
            -- hrbp_role,
            jf.job_family,
            jf.job_sub_family,
            st.job_level,
            st.job_level_code,
            REGEXP_REPLACE (st.l2_manager, r'\s*\(.*?\)', '') AS l2_manager,
            st.l2_manager_email,
            st.l2_manager_employee_id,
            st.latest_manager_effective_from,
            st.latest_modified,
            DATETIME(TIMESTAMP(PARSE_TIMESTAMP('%d-%b-%Y %H:%M:%S', st.latest_modified_timestamp)), 'Asia/Kolkata') AS latest_modified_timestamp,
            st.latest_modified_any_attribute,
            st.latest_office_effective_from,
            st.level,
            st.notice_period_assigned,
            st.notice_period_start_date,
            st.old_employee_id_rehired,
            st.past_work_experience,
            st.pay_scale,
            st.pay_scale_group,
            st.performance_manager,
            REGEXP_EXTRACT (st.performance_manager, r'^(.*) \(') AS performance_manager_name,
            REGEXP_EXTRACT (st.performance_manager, r'\((.*?)\)') AS performance_manager_id,
            st.permission_role,
            st.probation_period,
            st.retirement_date,
            st.retirement_date_manual,
            st.role,
            st.role_code,
            st.role_effective_from,
            st.role_name,
            st.salary_structure,
            st.separation_agreed_last_date,
            st.separation_final_recovery_days,
            st.separation_reject_reason,
            st.separation_requested_last_date,
            st.separation_revoke_date,
            st.separation_revoke_reason,
            st.separation_status,
            st.separation_transaction_date,
            st.termination_comment,
            st.vertical,
            st.vertical_code,
            st.base_office_location,
            st.blood_group,
            st.candidate_id,
            st.city_type,
            st.date_of_birth,
            st.date_of_birth_access,
            st.date_of_resignation_recorded,
            st.date_of_resignation,
            REGEXP_REPLACE (st.emergency_contact_number, r'[^0-9,]', '') AS emergency_contact_number,
            st.emergency_contact_person,
            st.emergency_contact_relation,
            st.location_type,
            st.marital_status,
            st.marriage_anniversary_access,
            st.office_area,
            st.office_city,
            st.office_country,
            st.office_location,
            st.office_pincode,
            st.office_state,
            st.office_city_code,
            st.office_country_code,
            st.office_state_code,
            st.phone_country_code,
            st.primary_mobile_number,
            st.primary_mobile_country_code,
            st.user_unique_id,
            st.work_area_code,
            st.citizenship,
            st.experience_prior_to_ather_round_off,
            st.fathers_name,
            st.food_allowance,
            st.job_title,
            st.personal_email_id,
            st.physical_work_location,
            st.`r_d_project_1`,
            st.`r_d_project_1_contribution`,
            st.`r_d_project_2`,
            st.`r_d_project_2_contribution`,
            st.`r_d_project_3`,
            st.`r_d_project_3_contribution`,
            st.`r_d_project_4`,
            st.`r_d_project_4_contributions`,
            st.`r_d_project_5`,
            st.`r_d_project_5_contribution`,
            st.special_leave_2022,
            st.swimlane_1,
            st.swimlane_1_contribution,
            st.swimlane_2,
            st.swimlane_2_contribution,
            st.swimlane_3,
            st.swimlane_3_contribution,
            st.swimlane_4,
            st.swimlane_4_contribution,
            st.swimlane_5,
            st.swimlane_5_contribution,
            st.current_address,
            st.current_address_line_1,
            st.current_pin_code,
            st.current_city,
            st.current_city_code,
            st.current_country,
            st.current_country_code,
            st.current_landmark,
            st.current_state,
            st.current_state_code,
            st.current_street,
            st.office_mobile_access,
            st.permanent_address,
            st.permanent_address_line_1,
            st.permanent_pin_code,
            st.permanent_city,
            st.permanent_city_code,
            st.permanent_country,
            st.permanent_country_code,
            st.permanent_district_code,
            st.permanent_landmark,
            st.permanent_region_code,
            st.permanent_state,
            st.permanent_state_code,
            st.permanent_street,
            st.personal_email_id_access,
            st.personal_mobile_access,
            TRIM(
                REGEXP_REPLACE (
                    REGEXP_REPLACE (st.personal_mobile_no, r'[^0-9,]', ''),
                    r'^,|,$',
                    ''
                )
            ) AS personal_mobile_no,
            st.home,
            TRIM(
                REGEXP_REPLACE (
                    REGEXP_REPLACE (st.office, r'[^0-9,]', ''),
                    r'^,|,$',
                    ''
                )
            ) AS office,
            TRIM(
                REGEXP_REPLACE (
                    REGEXP_REPLACE (st.personal, r'[^0-9,]', ''),
                    r'^,|,$',
                    ''
                )
            ) AS personal,
            TRIM(
                REGEXP_REPLACE (
                    REGEXP_REPLACE (st.office_mobile_no, r'[^0-9,]', ''),
                    r'^,|,$',
                    ''
                )
            ) AS office_mobile_no,
            st.gender,
            DATETIME (st.start_date, "Asia/Kolkata") AS start_date,
            DATETIME (st.end_date, "Asia/Kolkata") AS end_date,
            DATETIME (ts.ts, "Asia/Kolkata") AS load_timestamp,
        FROM
            `tt-sandbox-002.staging.st_db_emr` st
            LEFT JOIN `tt-sandbox-002.staging.st_gs_vdf` vdf ON CONCAT(
                TRIM(st.vertical),
                '|',
                COALESCE(
                TRIM(REGEXP_EXTRACT (st.departments_hierarchy_with_codes,r'\|\s*([^\(]+)')),
                TRIM(REGEXP_EXTRACT (st.departments_hierarchy_with_codes,r'^(.*?)\s*\('))),
                '|',
                COALESCE(
                TRIM(REGEXP_EXTRACT (st.departments_hierarchy_with_codes,r'^(.*?)\s*\(')),
                TRIM(REGEXP_EXTRACT (st.departments_hierarchy_with_codes,r'\|\s*([^\(]+)')))
            ) = TRIM(vdf.vdf)
            AND vdf.end_date IS NULL
            LEFT JOIN `tt-sandbox-002.staging.st_gs_jf` jf ON st.role_code = jf.role_code
            AND jf.end_date IS NULL
            LEFT JOIN `tt-sandbox-002.staging.st_db_emr` hrbp ON st.hrbp_employee_id = hrbp.employee_id
            AND hrbp.end_date IS NULL
            JOIN db_temp_timestamp ts ON 1 = 1;

            """,
            use_legacy_sql=False
        )

        trigger_transform_emr_child_merge = TriggerDagRunOperator(
        task_id="transform_merge_child_data",
        trigger_dag_id="transform_merge_child_data", 
        wait_for_completion=False, 
    )
   
start_task >> backup_tr_db_emr >> db_emr_transform_load>>trigger_transform_emr_child_merge
